
# This CI will launch a Docker image that contains all the dependencies required
# within that image the pytest test suite is run 


name: CI with examples

on:
  pull_request:    
    branches:
    - develop
    - main
 
jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: continuumio/miniconda3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: install package
        run: |
          pip install .
      
      - name: install cadquery as needed by the examples
        run: |
          conda install -c cadquery -c conda-forge cadquery=master

      - name: Run examples
        run: |
          cd examples
          python one_volume_cadquery_tesselation.py
          python one_volume_mesh.py
          python two_volume_mesh.py
